bases:
- ../environments.yaml
helmDefaults:
  atomic: true
  devel: false
  force: false
  recreatePods: false
  tillerless: false
  timeout: 520
  tls: false
  verify: false
  wait: true
releases:
- chart: zloeber/namespace
  name: namespace-nginx
  namespace: jx
  values:
  - generated/nginx/values.yaml
- chart: stable/nginx-ingress
  name: nginx-ingress
  namespace: nginx
  needs:
  - jx/namespace-nginx
  values:
  - /secrets/jenkins-x-versions/apps/stable/nginx-ingress/values.yaml.gotmpl
  - ../jx-requirements.values.yaml.gotmpl
  - /secrets/jx-boot/secrets.yaml
  version: 1.34.2
- chart: bitnami/external-dns
  name: external-dns
  namespace: jx
  values:
  - /secrets/jenkins-x-versions/apps/bitnami/external-dns/values.yaml.gotmpl
  - ../jx-requirements.values.yaml.gotmpl
  - /secrets/jx-boot/secrets.yaml
  - external-dns/values.yaml
  - external-dns/values.yaml.gotmpl
  version: 2.20.5
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: zloeber
  url: git+https://github.com/zloeber/helm-namespace@chart
